import Joi from 'joi';

export const validationSchema = Joi.object({
    PORT: Joi.number(),
    NODE_ENV: Joi.string().valid('development', 'production'),
    POSTGRES_HOST: Joi.string(),
    POSTGRES_PORT: Joi.number(),
    POSTGRES_DATABASE: Joi.string(),
    POSTGRES_USERNAME: Joi.string(),
    POSTGRES_PASSWORD: Joi.string(),
    POSTGRES_CERT_PATH: Joi.string().optional(),
    MONGO_URL: Joi.string(),
    JWT_ACCESS_SECRET: Joi.string(),
    JWT_ACCESS_EXPIRE: Joi.string(),
    JWT_REFRESH_SECRET: Joi.string(),
    JWT_REFRESH_EXPIRE: Joi.string(),
    SENDGRID_API_KEY: Joi.string(),
    STRIPE_API_KEY: Joi.string(),
    STRIPE_API_VERSION: Joi.string(),
    S3_ENDPOINT: Joi.string(),
    S3_ACCESS_KEY: Joi.string(),
    S3_SECRET_KEY: Joi.string(),
    S3_REGION: Joi.string(),
    S3_PUBLIC_CDN_URL_BASE: Joi.string(),
    PUBLIC_FILE_STORAGE_DIR: Joi.string(),
});
